### ISSUE TITLE
Trying test_sample.py fails with MuCAN models

### ISSUE THREAD

**Issue by moracabanas** [dvlab-research/Simple-SR#11]
I got this error 

```error
Processing: 386.png
Traceback (most recent call last):
  File "test_sample.py", line 113, in <module>
    output = model(lr_img)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/Simple-SR-master/exps/MuCAN_Vimeo90K/network.py", line 433, in forward
    B, N, C, H, W = x.size()
ValueError: not enough values to unpack (expected 5, got 4)
```

**Comment by fenglinglwb** [comment]
Did you set sr_type to VSR when testing?

**Comment by moracabanas** [comment]
Oh thanks I will try it!

**Comment by moracabanas** [comment]
> Did you set sr_type to VSR when testing?

I got this result:

```error
Loading Network ...
Traceback (most recent call last):
  File "test_sample.py", line 71, in <module>
    config, model = get_network(args.model_path)
  File "test_sample.py", line 14, in get_network
    if 'REDS' in model_path:
TypeError: argument of type 'NoneType' is not iterable
./run.sh: line 9: --model_path: command not found
```

**Comment by 3dsf** [comment]
I'm having trouble running the MuCAN models too

`python3 test_sample.py --sr_type VSR --model_path model/MuCAN_REDS.pth --input_path ./demo/LR_imgs --output_path ./demo/output
`

> RuntimeError: input1 must be contiguous

**Comment by fenglinglwb** [comment]
You can try to add tensor.contiguous() to get it run. It is caused by a different PyTorch version.

**Comment by sally-yuan** [comment]
I got the same error, any solutions?
**B, N, C, H, W = x.size()
ValueError: not enough values to unpack (expected 5, got 4)**
